<?php

namespace App\Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function index($method, $parameters)
    {
       return 0; // TODO: Change the autogenerated stub
    }
}
